name: avix
description: Avix messenger.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.5.5
  http: ^1.6.0
  cryptography: ^2.7.0
  mobile_scanner: ^7.2.0
  flutter_blue_plus: ^1.32.0
  wifi_direct_plugin: ^0.0.8
  permission_handler: ^11.0.0
  hive: ^2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
